mysite-Failed/mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
               path('polls/', include('polls.urls')),
               path('admin/', admin.site.urls),
]

mysite-Failed/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite-Failed/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite-Failed/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.ListView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

mysite-Failed/polls/templates/polls/PinelandMusicSchool.html
<!DOCTYPE html>
<html>
<head>
<!-- HTML Codes by Quackit.com -->
<title>
Music School </title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Pine Land Music School">
<style>
body {background-color:#a5feff;background-image:url(https://www.westernhills-music.com/wp-content/uploads/2018/03/music-staff_b1d89oyes__F0000.png);background-repeat:no-repeat;background-position:top left;background-attachment:scroll;}
h1{font-family:Arial, sans-serif;color:#000000;background-color:#ffffff;}
p {font-family:Georgia, serif;font-size:14px;font-style:normal;font-weight:normal;color:#000000;background-color:#ffffff;}
</style>
</head>
<body>
<h1>WELCOME TO PINELAND MUSIC SCHOOL</h1>
<p>lkslkcnaslkfknleknflkenflnlaknflakenfeklanflkenflkanfa</p>
</body>
</html>

mysite-Failed/polls/templates/polls/detail.html
<html>

<head>

<style>
table#t01, th, td{
    border: 0px solid black;
    border-collapse: collapse;
    padding: 15px;
}
table#t01 th, td {
    padding: 15px;
}
    table#t01, th {
    font-family: Impact, Charcoal, sans-serif;
    }
table#t01 {
    background-color: #D4DCFF;
    text-align: center;
    }
.book_button {
    background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    text-decoration: none;
    }

    </style>

<title>Lessons</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


<body>

<h1>
        <img src="../../static/polls/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
</h1>

            <div class="topnav">
            <a href={% url 'polls:index' %}>Home</a>
            <a href={% url 'polls:index/1' %}>Book Lessons</a>
            <a href="hiring_info.html">Hire Instruments</a>
            <a href="#">Our Teachers</a>
            <a href="Login.html">Login</a>
        </div>

    <h1>Our Lesson Services</h1>

    <table style="width:50%" id="t01" align="center">
  <tr>
    <th style="width: 10%">Instrument</th>
    <th style="width: 10%">Cost/Week</th>
    <th style="width: 10%">Teacher</th>
    <th></th>
  </tr>
  <tr>
    <td>Guitar</td>
    <td>$30</td>
    <td>Natalie</td>
    <td style="color: orange">You must login to book a lesson.</td>
  </tr>
  <tr>
    <td>Drums</td>
    <td>$30</td>
    <td>Dan</td>
    <td style="color: orange">You must login to book a lesson.</td>
  </tr>
  <tr>
    <td>Viola</td>
    <td>$30</td>
    <td>Thelma</td>
    <td style="color: orange">You must login to book a lesson.</td>
  </tr>
  <tr>
    <td>French Horn</td>
    <td>$30</td>
    <td>Jonathan</td>
    <td style="color: orange">You must login to book a lesson.</td>
  </tr>
        <tr>
    <td>Piano</td>
    <td>$30</td>
    <td>Margaret</td>
    <td style="color: orange">You must login to book a lesson.</td>
  </tr>
</table>


    <table style="height: 72px; width: 100%; margin-top: 20px">
<tbody>
<tr>
    <td style="width: 188px; text-align: center;"><span style="color: green," >OPENING HOURS</span></td>
<td style="width: 183px;">
<div class="header-block align-header-left" style="text-align: center;">
<div class="title"><span class="ng-binding ng-scope" style="color: green" >SUBSCRIBE FOR UPDATES</span></div>
</div>
</td>
    <td style="width: 165px; text-align: center"><span style="color: green" >ADDRESS</span></td>
</tr>
<tr>
<td style="width: 188px;">
<p class="font_9" style="text-align: center;"><span class="color_13">Monday-Friday</span>&nbsp;</p>
<p class="font_9" style="text-align: center;">7:00am-10:00pm</p>
<p class="font_9" style="text-align: center;"><span class="color_13">Saturday-Sunday</span>&nbsp;</p>
<p class="font_9" style="text-align: center;">7:00am-8:00pm</p>
</td>
<td style="width: 183px; text-align: center" >
    Email:<br>
    <input type="text" name="lastname">
    <br>

    <br><input type="submit" value="Submit">

</td>
<td style="width: 165px;">
<p class="font_9" style="text-align: center;">500 Terry Francois St. San Francisco, CA 94158</p>
<p class="font_9" style="text-align: center;">Tel: 123-456-7890</p>
</td>
</tr>
</tbody>
</table>

</body>
</head>
</html>

mysite-Failed/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<head>

    <script type="text/javascript">
        <!-->
        var image1 = new Image()
        image1.src = "../../static/polls/images/Slide1.jpg"
        var image2 = new Image()
        image2.src = "../../static/polls/images/Slide2.jpg"
        var image3 = new Image()
        image3.src = "../../static/polls/images/Slide3.jpg"
        //-->


    </script>

    <title>Music School </title>


    <body>

        <h1>

        <img src="../../static/polls/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
</h1>
        <div class="topnav">
            <a href={% url 'polls:index' %}>Home</a>
            <a href={% url 'polls:detail' %}>Book Lessons</a>
            <a href="hiring_info.html">Hire Instruments</a>
            <a href="#">Our Teachers</a>
            <a href="Login.html">Login</a>
        </div>


        <img src="../../static/polls/images/Slide1.jpg" name="slide" width="100%" height="450">

        <script type="text/javascript">
            <!--
            var step = 1

            function slideit() {
                document.images.slide.src = eval("image" + step + ".src")
                if (step < 3)
                    step++

                    else step = 1 setTimeout("slideit()", 2500)
            }
            slideit() //-->
        </script>

        <div class="container">


            <div class="gallery">

                <a href="lesson_info.html">
                    <img src="../../static/polls/images/Guitar.jpg" alt="Guitar1" width="300" height="200">
                </a>
                <div class="desc">Book Lessons</div>
            </div>

            <div class="gallery">

                <a href="hiring_info.html">
                    <img src="../../static/polls/images/guitar2.jpg" alt="Guitar2" width="600" height="400">
                </a>
                <div class="desc">Hire Instruments</div>
            </div>

            <div class="gallery">
                <a href="#">
                    <img src="../../static/polls/images/Teachers.jpg" alt="Teachers" width="600" height="400">
                </a>
                <div class="desc">Our Teachers</div>
            </div>
        </div>

        <div class="table1">
            <table class="Table1">
                <tbody>
                    <tr>
                        <td style="font-family: sans-serif; padding-left: 100px"><span style="color: darkslategray">
From private lessons in the comfort of your own home, to
yearly programs in our fully equipped classrooms, Key Lessons
    will find the way to bring the love of music into your life</span></td>
                        <td style="padding-right: 70px"><img src="../../static/polls/images/Tree.jpg" align="center" alt="tree" height="200px" width="420px"></td>
                        <td style="font-family: sans-serif; padding-right: 100px"><span style="color: darkslategray">Call now for a FREE first lesson. The number is 123-456-7890</span></td>
                    </tr>
                </tbody>
            </table>

        </div>

        <table style="height: 72px; width: 100%; margin-top: 20px">
            <tbody>
                <tr>
                    <td style="width: 188px; text-align: center;"><span style="color: green,">OPENING HOURS</span></td>
                    <td style="width: 183px;">
                        <div class="header-block align-header-left" style="text-align: center;">
                            <div class="title"><span class="ng-binding ng-scope" style="color: green">SUBSCRIBE FOR UPDATES</span></div>
                        </div>
                    </td>
                    <td style="width: 165px; text-align: center"><span style="color: green">ADDRESS</span></td>
                </tr>
                <tr>
                    <td style="width: 188px;">
                        <p class="font_9" style="text-align: center;"><span class="color_13">Monday-Friday</span>&nbsp;</p>
                        <p class="font_9" style="text-align: center;">7:00am-10:00pm</p>
                        <p class="font_9" style="text-align: center;"><span class="color_13">Saturday-Sunday</span>&nbsp;</p>
                        <p class="font_9" style="text-align: center;">7:00am-8:00pm</p>
                    </td>
                    <td style="width: 183px; text-align: center">

                        Email:<br>
                        <input type="text" name="lastname">
                        <br>

                        <br><input type="submit" value="Submit">

                    </td>
                    <td style="width: 165px;">
                        <p class="font_9" style="text-align: center;">500 Terry Francois St. San Francisco, CA 94158</p>
                        <p class="font_9" style="text-align: center;">Tel: 123-456-7890</p>
                    </td>
                </tr>
            </tbody>
        </table>

    </body>
</head>

</html>

mysite-Failed/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>