mysite copy/PinelandsMusicSchool/urls.py
from django.urls import path
from . import views

app_name = 'PinelandsMusicSchool'
urlpatterns = [
    path('', views.index, name='index'),
    path('Book_lessons', views.Book_lessons, name= 'Book_lessons'),
    path('Book_lessons/Piano', views.book_piano, name= 'book_piano'),
    path('Hiring_info', views.hiring_info, name= 'hiring_info'),
    path('Hiring_info/Sax', views.hiring_form_sax, name = 'hiring_form_sax'),
    path('Hiring_info/Guitar', views.hiring_form_guitar, name = 'hiring_form_guitar'),
    path('Hiring_info/Flute', views.hiring_form_flute, name = 'hiring_form_flute'),
    path('Hiring_info/Clarinet', views.hiring_form_clarinet, name = 'hiring_form_clarinet'),
    path('Login', views.Login, name='Login'),
    path('Login/create_account', views.create_account, name= 'create_account'),
    path('Student', views.index_student, name= 'index_student'),
    path('Teacher', views.index_Teacher, name= 'index_Teacher'),


]

mysite copy/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PinelandsMusicSchool/', include('PinelandsMusicSchool.urls')),

]

mysite copy/PinelandsMusicSchool/models.py
from django.db import models

# Create your models here.
class Accounts (models.Model):
    First_name = models.CharField(max_length=250)
    Last_name = models.CharField(max_length=250)
    Email = models.CharField(max_length=100)
    Age = models.CharField(max_length=4)
    Password = models.CharField(max_length=100)



      

mysite copy/PinelandsMusicSchool/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic



#def index(request):
#    return render(request, 'PinelandsMusicSchool/index.html')


def index(request):
    return render(request, 'PinelandsMusicSchool/index.html')

def Book_lessons(request):
    return render(request, 'PinelandsMusicSchool/lesson_info.html')

def book_piano(request):
    return render(request, 'PinelandsMusicSchool/book_piano.html')

def hiring_info(request):
    return render(request, 'PinelandsMusicSchool/hiring_info.html')

def hiring_form_sax(request):
    return render(request, 'PinelandsMusicSchool/hiring_form_sax.html')

def hiring_form_guitar(request):
    return render(request, 'PinelandsMusicSchool/hiring_form_guitar.html')

def hiring_form_flute(request):
    return render(request, 'PinelandsMusicSchool/hiring_form_flute.html')

def hiring_form_clarinet(request):
    return render(request, 'PinelandsMusicSchool/hiring_form_clarinet.html')

def Login(request):
    return render(request, 'PinelandsMusicSchool/Login.html')

def create_account(request):
    return render(request, 'PinelandsMusicSchool/create_account.html')

def index_student(request):
    return render(request, 'PinelandsMusicSchool/index_student.html')

def index_Teacher(request):
    return render(request, 'PinelandsMusicSchool/index_Teacher.html')

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/Login.html
<!DOCTYPE html>
<html>

<head>

    <title>Music School </title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />


    <body>

        <h1>
            <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align="left" name="Banner" width="350" height="85" margin-bottom="10px">
        </h1>
        <div class="topnav">
        <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
        <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
        <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
        <a href="#">Our Teachers</a>
        <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
      </div>

        <div class="loginbox">
            <h2>Login Here</h2>
            <form>
                <m>Username</m>
                <input type="text" name="" placeholder="Enter Username">
                <m>Password</m>
                <input type="password" name="" placeholder="Enter Password">
                <input type="submit" name="" placeholder="Login">
                <a href= {% url 'PinelandsMusicSchool:create_account' %}>Create your account </a>
        </form>

        </div>






        <table style="height: 72px; width: 100%; margin-top: 20px">
            <tbody>
                <tr>
                    <td style="width: 188px; text-align: center;"><span style="color: green,">OPENING HOURS</span></td>
                    <td style="width: 183px;">
                        <div class="header-block align-header-left" style="text-align: center;">
                            <div class="title"><span class="ng-binding ng-scope" style="color: green">SUBSCRIBE FOR UPDATES</span></div>
                        </div>
                    </td>
                    <td style="width: 165px; text-align: center"><span style="color: green">ADDRESS</span></td>
                </tr>
                <tr>
                    <td style="width: 188px;">
                        <p class="font_9" style="text-align: center;"><span class="color_13">Monday-Friday</span>&nbsp;</p>
                        <p class="font_9" style="text-align: center;">7:00am-10:00pm</p>
                        <p class="font_9" style="text-align: center;"><span class="color_13">Saturday-Sunday</span>&nbsp;</p>
                        <p class="font_9" style="text-align: center;">7:00am-8:00pm</p>
                    </td>
                    <td style="width: 183px; text-align: center">
                        Email:<br>
                        <input type="text" name="lastname">
                        <br>

                        <br><input type="submit" value="Submit">

                    </td>
                    <td style="width: 165px;">
                        <p class="font_9" style="text-align: center;">500 Terry Francois St. San Francisco, CA 94158</p>
                        <p class="font_9" style="text-align: center;">Tel: 123-456-7890</p>
                    </td>
                </tr>
            </tbody>
        </table>

    </body>
</head>

</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/book_piano.html
<!DOCTYPE html>
<html>
<head>

<title>Book Piano Lessons</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 80%;
    text-align: left;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

input[type=text], input[type=password] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
        margin-top: 20px;
    }

</style>
</head>
<body>

  <h1>
        <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
</h1>
      <div class="topnav">
      <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
      <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
      <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
      <a href="#">Our Teachers</a>
      <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
    </div>

<h1>Booking Piano Lessons</h1>

<div class="container">
<form>
  I require lessons from:
  <input type="date" name="hire_date">
    To:
    <input type="date" name="hire_date">
    <br>
    What day would you like to have lessons on?<br>
  <select name="day">
    <option value="monday">Monday</option>
    <option value="tuesday">Tuesday</option>
    <option value="wednesday">Wednesday</option>
    <option value="thursday">Thursday</option>
    <option value="friday">Friday</option>
  </select>
    <br>
    What time would you like your lessons?
  <input type="Time" name="time">
    <br>

    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>


</body>
</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/create_account.html
<!DOCTYPE html>
<html>
<head>

<title>Create Account</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 100%;
    text-align: center;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

input[type=text], input[type=password] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
    }

</style>

    <script type="text/javascript">

function yesnoCheck() {
    if (document.getElementById('yesCheck').checked) {
        document.getElementById('ifYes').style.display = 'block';
    }
    else document.getElementById('ifYes').style.display = 'none';
}


</script>

</head>

  <h1>
        <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
</h1>
      <div class="topnav">
      <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
      <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
      <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
      <a href="#">Our Teachers</a>
      <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
    </div>

<h1>Create an account</h1>

<div class="container">
<form action="/action_page.php" method="post">
  First name:<br>
  <input type="text" name="firstname" required>
  <br>
  Last name:<br>
  <input type="text" name="lastname">
  <br>
  Email:<br>
  <input type="text" name="lastname">
  <br>
  Age:<br>
  <input type="text" name="lastname">
  <br>
  Password:<br>
  <input type="Password" name="lastname">
  <br>
  Password again:<br>
  <input type="Password" name="lastname">
  <br>
  Gender:<br>
  <input type="radio" name="gender" value="male" checked> Male<br>
  <input type="radio" name="gender" value="female"> Female<br>
  <input type="radio" name="gender" value="other"> Other
  <br>
  Phone Number:<br>
  <input type="text" name="lastname">
  <br>
  Phone Number (2):<br>
  <input type="text" name="lastname">
  <br>

    Are you under the age of 18?
    <br>
Yes <input type="radio" onclick="javascript:yesnoCheck();" name="yesno" id="yesCheck"> No <input type="radio" onclick="javascript:yesnoCheck();" name="yesno" id="noCheck"><br>
    <div id="ifYes" style="display:none">
        <h2>Please fill out the following information:</h2>
  <h2>Guardian 1</h2>
  First name:<br>
  <input type="text" name="firstname">
  <br>
  Last name:<br>
  <input type="text" name="lastname">
  <br>
  Relation:<br>
  <input type="text" name="lastname">
  <br>
  Phone Number:<br>
  <input type="text" name="lastname">
  <br>
  Email:<br>
  <input type="text" name="lastname">
  <br>

 <h2>Guardian 2</h2>
  First name:<br>
  <input type="text" name="firstname">
  <br>
  Last name:<br>
  <input type="text" name="lastname">
  <br>
  Relation:<br>
  <input type="text" name="lastname">
  <br>
  Phone Number:<br>
  <input type="text" name="lastname">
  <br>
  Email:<br>
  <input type="text" name="lastname">
  <br>
</div>

    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>



</body>
</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/hiring_form_clarinet.html
<!DOCTYPE html>
<html>
<head>

<title>Hiring Clarinet Form</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 100%;
    text-align: center;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

input[type=text], input[type=password] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
    }

</style>
</head>
<body>

  <h1>
          <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
  </h1>

  <div class="topnav">
  <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
  <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
  <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
  <a href="#">Our Teachers</a>
  <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
  </div>
<h1>Hiring Clarinet Form</h1>

<div class="container">
<form>
  I will need to hire this instrument from:
  <input type="date" name="hire_date">
    To:
    <input type="date" name="hire_date">
    <br>
    Will you require reeds?
    <input type="radio" name="pick" value="yes_pick"> Yes<br>
  <input type="radio" name="pick" value="no_pick"> No<br>
    <br>
        Do you have lessons with us using this instrument?
    <input type="radio" name="lessons_enquiry" value="yes_pick"> Yes<br>
  <input type="radio" name="lessons_enquiry" value="no_pick"> No<br>



    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>



</body>
</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/hiring_form_flute.html
<!DOCTYPE html>
<html>
<head>

<title>Hiring Flute Form</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 100%;
    text-align: center;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

input[type=text], input[type=password] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
    }

</style>
</head>
<body>

  <h1>
          <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
  </h1>

  <div class="topnav">
  <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
  <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
  <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
  <a href="#">Our Teachers</a>
  <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
  </div>

<h1>Hiring Flute Form</h1>

<div class="container">
<form>
  I will need to hire this instrument from:
  <input type="date" name="hire_date">
    To:
    <input type="date" name="hire_date">
    <br>
        Do you have lessons with us using this instrument?
    <input type="radio" name="lessons_enquiry" value="yes_pick"> Yes<br>
  <input type="radio" name="lessons_enquiry" value="no_pick"> No<br>



    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>


</body>
</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/hiring_form_guitar.html
<!DOCTYPE html>
<html>
<head>

<title>Hiring Guitar Form</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 100%;
    text-align: center;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

    input[type=text], input[type=password], input[type=date] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
    }

</style>
</head>
<body>

  <h1>
          <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
  </h1>

  <div class="topnav">
  <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
  <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
  <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
  <a href="#">Our Teachers</a>
  <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
  </div>

<h1>Hiring Guitar Form</h1>

<div class="container">
<form>
  I will need to hire this instrument from:
  <input type="date" name="hire_date">
    To:
    <input type="date" name="hire_date">
    <br>
    Will you require a pick?
    <input type="radio" name="pick" value="yes_pick"> Yes<br>
  <input type="radio" name="pick" value="no_pick"> No<br>
    <br>
        Do you have lessons with us using this instrument?
    <input type="radio" name="lessons_enquiry" value="yes_pick"> Yes<br>
  <input type="radio" name="lessons_enquiry" value="no_pick"> No<br>



    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>



</body>
</html>

mysite copy/PinelandsMusicSchool/templates/PinelandsMusicSchool/hiring_form_sax.html
<!DOCTYPE html>
<html>
<head>

<title>Hiring Saxophone Form</title>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'PinelandsMusicSchool/style.css' %}" />

<style>

body {background-color: white;}

h1   {color: darkgreen;
    font-family: verdana;
    font-size: 200%;
  text-align: center;}

p    {color: black;
      font-family: verdana;
      font-size: 100%;
    text-align: center;}

h2 {color: black;
    font-family: verdana;
    font-size: 100%;
    text-align: center;}

.container {
  width: 50%;
  clear: both;
  padding-left: 25%;
  font-family: verdana;
}

.container input {
  width: 100%;
  clear: both;
}

input[type=text], input[type=password] {border-top-style: none;
    border-right-style: none;
    border-bottom-style: solid;
    border-left-style: none;
    border-color: lightgreen;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;}

input[type=submit] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;}

input[type=cancel] {background-color: orange;
      width: 20%;
      padding: 10px 10px;
      font-size: 100%;
      color: white;
    margin-left: 10px;}

    .submit_cancel a {
        color: white;
        padding: 10px;
        margin-right: 20px;
        background-color: orange;
        text-decoration: none;
        display: inline-block;
        border-radius: 2px;
        width: 20%;
        text-align: center;
    }

</style>
</head>
<body>

  <h1>
          <img src="../../static/PinelandsMusicSchool/images/Banner_Image.png" align= "left" name="Banner" width="350" height="85" margin-bottom="10px" >
  </h1>

  <div class="topnav">
  <a href= {% url 'PinelandsMusicSchool:index' %}>Home</a>
  <a href= {% url 'PinelandsMusicSchool:Book_lessons' %}>Book Lessons</a>
  <a href= {% url 'PinelandsMusicSchool:hiring_info' %}>Hire Instruments</a>
  <a href="#">Our Teachers</a>
  <a href= {% url 'PinelandsMusicSchool:Login' %}>Login</a>
  </div>

<h1>Hiring Saxophone Form</h1>

<div class="container">
<form>
  I will need to hire this instrument from:
  <input type="date" name="hire_date">
    To:
    <input type="date" name="hire_date">
    <br>
    Will you require reeds?
    <input type="radio" name="pick" value="yes_pick"> Yes<br>
  <input type="radio" name="pick" value="no_pick"> No<br>
    <br>
        Do you have lessons with us using this instrument?
    <input type="radio" name="lessons_enquiry" value="yes_pick"> Yes<br>
  <input type="radio" name="lessons_enquiry" value="no_pick"> No<br>



    <div class="submit_cancel">
        <a href="#">Submit</a>
        <a href="index.html">Cancel</a>
    </div>

</form>
</div>


</body>
</html>